[project]
name = "atrgnfp-buy-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
]
